#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>
#include <stdio.h>

/* generated by fbt from .png files in images folder */
#include <starter_app_icons.h>

#define TAG "starter_app"

typedef struct {
    uint32_t ok_press_count;
} StarterAppState;

typedef struct {
    InputEvent input;
} StarterAppEvent;

static void starter_app_draw_callback(Canvas* canvas, void* context) {
    StarterAppState* state = context;

    canvas_clear(canvas);
    canvas_set_bitmap_mode(canvas, 1);
    canvas_draw_icon(canvas, 4, 4, &I_starter_app_10px);

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 18, 13, "Starter App");

    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str(canvas, 4, 28, "Press OK to increment.");
    canvas_draw_str(canvas, 4, 39, "Press BACK to exit.");

    char counter_text[32];
    snprintf(counter_text, sizeof(counter_text), "Count: %lu", state->ok_press_count);
    canvas_draw_str(canvas, 4, 56, counter_text);
}

static void starter_app_input_callback(InputEvent* input_event, void* context) {
    FuriMessageQueue* event_queue = context;
    StarterAppEvent event = {.input = *input_event};
    furi_message_queue_put(event_queue, &event, FuriWaitForever);
}

int32_t starter_app_app(void* p) {
    UNUSED(p);

    StarterAppState state = {0};
    StarterAppEvent event;
    bool running = true;

    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(StarterAppEvent));
    ViewPort* view_port = view_port_alloc();
    Gui* gui = furi_record_open(RECORD_GUI);

    view_port_draw_callback_set(view_port, starter_app_draw_callback, &state);
    view_port_input_callback_set(view_port, starter_app_input_callback, event_queue);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    while(running) {
        FuriStatus status = furi_message_queue_get(event_queue, &event, FuriWaitForever);
        if(status != FuriStatusOk) {
            continue;
        }

        if(event.input.type != InputTypeShort) {
            continue;
        }

        if(event.input.key == InputKeyBack) {
            running = false;
        } else if(event.input.key == InputKeyOk) {
            state.ok_press_count++;
            FURI_LOG_I(TAG, "OK pressed %lu time(s)", state.ok_press_count);
            view_port_update(view_port);
        }
    }

    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_record_close(RECORD_GUI);
    furi_message_queue_free(event_queue);

    return 0;
}
